parameters:
    secret: null
    locale: null
    mailer_transport: gmail
    mailer_host: null
    mailer_user: null
    mailer_password: 
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_user: null
    database_password: null
    database_name: null
    database_path: null
