<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121222165858 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE PackExport (id INT AUTO_INCREMENT NOT NULL, created_by INT NOT NULL, pack_id INT NOT NULL, language_id INT NOT NULL, filepath VARCHAR(255) NOT NULL, created DATETIME NOT NULL, INDEX IDX_32B1769FDE12AB56 (created_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE PackExport ADD CONSTRAINT FK_32B1769FDE12AB56 FOREIGN KEY (created_by) REFERENCES User (id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE PackExport");
    }
}
