<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121215115035 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE TranslationSubmission (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, classification_id INT NOT NULL, translation_id INT NOT NULL, created DATETIME NOT NULL, INDEX IDX_ACE7B56DA76ED395 (user_id), INDEX IDX_ACE7B56D2A86559F (classification_id), UNIQUE INDEX UNIQ_ACE7B56D9CAA2B25 (translation_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE TranslationSubmission ADD CONSTRAINT FK_ACE7B56DA76ED395 FOREIGN KEY (user_id) REFERENCES User (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE TranslationSubmission ADD CONSTRAINT FK_ACE7B56D2A86559F FOREIGN KEY (classification_id) REFERENCES Classification (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE TranslationSubmission ADD CONSTRAINT FK_ACE7B56D9CAA2B25 FOREIGN KEY (translation_id) REFERENCES Translation (id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE TranslationSubmission");
    }
}
