<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121213220105 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE MessagesImport DROP FOREIGN KEY FK_68BC7D141919B217");
        $this->addSql("ALTER TABLE MessagesImport ADD CONSTRAINT FK_68BC7D141919B217 FOREIGN KEY (pack_id) REFERENCES Pack (id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE MessagesImport DROP FOREIGN KEY FK_68BC7D141919B217");
        $this->addSql("ALTER TABLE MessagesImport ADD CONSTRAINT FK_68BC7D141919B217 FOREIGN KEY (pack_id) REFERENCES Pack (id)");
    }
}
