<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121218101214 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE Classification (id INT AUTO_INCREMENT NOT NULL, messages_import_id INT NOT NULL, message_id INT NOT NULL, pack_id INT NOT NULL, category VARCHAR(64) NOT NULL, section VARCHAR(64) DEFAULT NULL, subsection VARCHAR(64) DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_880FAAE9B868F34B (messages_import_id), INDEX IDX_880FAAE9537A1329 (message_id), INDEX IDX_880FAAE91919B217 (pack_id), UNIQUE INDEX pack_id_message_id_idx (pack_id, message_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE TranslationsImport (id INT AUTO_INCREMENT NOT NULL, created_by INT NOT NULL, original_filename VARCHAR(255) NOT NULL, filepath VARCHAR(255) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_12D3AC52DE12AB56 (created_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Pack (id INT AUTO_INCREMENT NOT NULL, project VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, version VARCHAR(255) NOT NULL, created_by INT NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, UNIQUE INDEX project_name_version_idx (project, name, version), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Language (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, locale VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE User (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(255) NOT NULL, username_canonical VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, email_canonical VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, locked TINYINT(1) NOT NULL, expired TINYINT(1) NOT NULL, expires_at DATETIME DEFAULT NULL, confirmation_token VARCHAR(255) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT '(DC2Type:array)', credentials_expired TINYINT(1) NOT NULL, credentials_expire_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_2DA1797792FC23A8 (username_canonical), UNIQUE INDEX UNIQ_2DA17977A0D96FBF (email_canonical), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE CurrentTranslation (id INT AUTO_INCREMENT NOT NULL, classification_id INT NOT NULL, translation_id INT NOT NULL, language_id INT NOT NULL, INDEX IDX_D3434B822A86559F (classification_id), INDEX IDX_D3434B829CAA2B25 (translation_id), UNIQUE INDEX classification_id_language_id_idx (classification_id, language_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Storage (id INT AUTO_INCREMENT NOT NULL, messages_import_id INT NOT NULL, pack_id INT NOT NULL, message_id INT NOT NULL, method VARCHAR(64) NOT NULL, path VARCHAR(255) NOT NULL, category VARCHAR(64) NOT NULL, custom VARCHAR(64) DEFAULT NULL, INDEX IDX_9BC722A8B868F34B (messages_import_id), INDEX IDX_9BC722A81919B217 (pack_id), INDEX IDX_9BC722A8537A1329 (message_id), UNIQUE INDEX pack_id_message_id_idx (pack_id, message_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Translation (id INT AUTO_INCREMENT NOT NULL, translations_import_id INT DEFAULT NULL, created_by INT DEFAULT NULL, reviewed_by INT DEFAULT NULL, language_id INT NOT NULL, previous_translation_id INT DEFAULT NULL, mkey LONGTEXT NOT NULL, text LONGTEXT NOT NULL, INDEX IDX_32F5CAB8D306E14 (translations_import_id), INDEX IDX_32F5CAB8DE12AB56 (created_by), INDEX IDX_32F5CAB885D7FB47 (reviewed_by), INDEX IDX_32F5CAB882F1BAF4 (language_id), INDEX mkey_language_id_text_idx (mkey (255), language_id, text (255)), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE MessagesImport (id INT AUTO_INCREMENT NOT NULL, pack_id INT NOT NULL, original_filename VARCHAR(255) NOT NULL, filepath VARCHAR(255) NOT NULL, created_by INT NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_68BC7D141919B217 (pack_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE TranslationSubmission (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, classification_id INT NOT NULL, translation_id INT NOT NULL, created DATETIME NOT NULL, INDEX IDX_ACE7B56DA76ED395 (user_id), INDEX IDX_ACE7B56D2A86559F (classification_id), UNIQUE INDEX UNIQ_ACE7B56D9CAA2B25 (translation_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Message (id INT AUTO_INCREMENT NOT NULL, messages_import_id INT NOT NULL, mkey VARCHAR(255) NOT NULL, text LONGTEXT NOT NULL, type VARCHAR(32) NOT NULL, INDEX IDX_790009E3B868F34B (messages_import_id), UNIQUE INDEX mkey_idx (mkey), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE Classification ADD CONSTRAINT FK_880FAAE9B868F34B FOREIGN KEY (messages_import_id) REFERENCES MessagesImport (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE Classification ADD CONSTRAINT FK_880FAAE9537A1329 FOREIGN KEY (message_id) REFERENCES Message (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE Classification ADD CONSTRAINT FK_880FAAE91919B217 FOREIGN KEY (pack_id) REFERENCES Pack (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE TranslationsImport ADD CONSTRAINT FK_12D3AC52DE12AB56 FOREIGN KEY (created_by) REFERENCES User (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE CurrentTranslation ADD CONSTRAINT FK_D3434B822A86559F FOREIGN KEY (classification_id) REFERENCES Classification (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE CurrentTranslation ADD CONSTRAINT FK_D3434B829CAA2B25 FOREIGN KEY (translation_id) REFERENCES Translation (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE Storage ADD CONSTRAINT FK_9BC722A8B868F34B FOREIGN KEY (messages_import_id) REFERENCES MessagesImport (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE Storage ADD CONSTRAINT FK_9BC722A81919B217 FOREIGN KEY (pack_id) REFERENCES Pack (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE Storage ADD CONSTRAINT FK_9BC722A8537A1329 FOREIGN KEY (message_id) REFERENCES Message (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE Translation ADD CONSTRAINT FK_32F5CAB8D306E14 FOREIGN KEY (translations_import_id) REFERENCES TranslationsImport (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE Translation ADD CONSTRAINT FK_32F5CAB8DE12AB56 FOREIGN KEY (created_by) REFERENCES User (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE Translation ADD CONSTRAINT FK_32F5CAB885D7FB47 FOREIGN KEY (reviewed_by) REFERENCES User (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE Translation ADD CONSTRAINT FK_32F5CAB882F1BAF4 FOREIGN KEY (language_id) REFERENCES Language (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE MessagesImport ADD CONSTRAINT FK_68BC7D141919B217 FOREIGN KEY (pack_id) REFERENCES Pack (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE TranslationSubmission ADD CONSTRAINT FK_ACE7B56DA76ED395 FOREIGN KEY (user_id) REFERENCES User (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE TranslationSubmission ADD CONSTRAINT FK_ACE7B56D2A86559F FOREIGN KEY (classification_id) REFERENCES Classification (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE TranslationSubmission ADD CONSTRAINT FK_ACE7B56D9CAA2B25 FOREIGN KEY (translation_id) REFERENCES Translation (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE Message ADD CONSTRAINT FK_790009E3B868F34B FOREIGN KEY (messages_import_id) REFERENCES MessagesImport (id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE CurrentTranslation DROP FOREIGN KEY FK_D3434B822A86559F");
        $this->addSql("ALTER TABLE TranslationSubmission DROP FOREIGN KEY FK_ACE7B56D2A86559F");
        $this->addSql("ALTER TABLE Translation DROP FOREIGN KEY FK_32F5CAB8D306E14");
        $this->addSql("ALTER TABLE Classification DROP FOREIGN KEY FK_880FAAE91919B217");
        $this->addSql("ALTER TABLE Storage DROP FOREIGN KEY FK_9BC722A81919B217");
        $this->addSql("ALTER TABLE MessagesImport DROP FOREIGN KEY FK_68BC7D141919B217");
        $this->addSql("ALTER TABLE Translation DROP FOREIGN KEY FK_32F5CAB882F1BAF4");
        $this->addSql("ALTER TABLE TranslationsImport DROP FOREIGN KEY FK_12D3AC52DE12AB56");
        $this->addSql("ALTER TABLE Translation DROP FOREIGN KEY FK_32F5CAB8DE12AB56");
        $this->addSql("ALTER TABLE Translation DROP FOREIGN KEY FK_32F5CAB885D7FB47");
        $this->addSql("ALTER TABLE TranslationSubmission DROP FOREIGN KEY FK_ACE7B56DA76ED395");
        $this->addSql("ALTER TABLE CurrentTranslation DROP FOREIGN KEY FK_D3434B829CAA2B25");
        $this->addSql("ALTER TABLE TranslationSubmission DROP FOREIGN KEY FK_ACE7B56D9CAA2B25");
        $this->addSql("ALTER TABLE Classification DROP FOREIGN KEY FK_880FAAE9B868F34B");
        $this->addSql("ALTER TABLE Storage DROP FOREIGN KEY FK_9BC722A8B868F34B");
        $this->addSql("ALTER TABLE Message DROP FOREIGN KEY FK_790009E3B868F34B");
        $this->addSql("ALTER TABLE Classification DROP FOREIGN KEY FK_880FAAE9537A1329");
        $this->addSql("ALTER TABLE Storage DROP FOREIGN KEY FK_9BC722A8537A1329");
        $this->addSql("DROP TABLE Classification");
        $this->addSql("DROP TABLE TranslationsImport");
        $this->addSql("DROP TABLE Pack");
        $this->addSql("DROP TABLE Language");
        $this->addSql("DROP TABLE User");
        $this->addSql("DROP TABLE CurrentTranslation");
        $this->addSql("DROP TABLE Storage");
        $this->addSql("DROP TABLE Translation");
        $this->addSql("DROP TABLE MessagesImport");
        $this->addSql("DROP TABLE TranslationSubmission");
        $this->addSql("DROP TABLE Message");
    }
}
