<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121223180126 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE Country (id INT AUTO_INCREMENT NOT NULL, iso_code VARCHAR(16) NOT NULL, ps_code VARCHAR(16) NOT NULL, map�_code VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE CountryLanguage (id INT AUTO_INCREMENT NOT NULL, country_id INT NOT NULL, language_id INT NOT NULL, percent DOUBLE PRECISION NOT NULL, INDEX IDX_186C946DF92F3E70 (country_id), INDEX IDX_186C946D82F1BAF4 (language_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE CountryLanguage ADD CONSTRAINT FK_186C946DF92F3E70 FOREIGN KEY (country_id) REFERENCES Country (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE CountryLanguage ADD CONSTRAINT FK_186C946D82F1BAF4 FOREIGN KEY (language_id) REFERENCES Language (id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE CountryLanguage DROP FOREIGN KEY FK_186C946DF92F3E70");
        $this->addSql("DROP TABLE Country");
        $this->addSql("DROP TABLE CountryLanguage");
    }
}
