homepage:
    pattern:  /
    defaults: { _controller: FMSymSlateBundle:Default:index }

packs:
    resource: "@FMSymSlateBundle/Controller/PackController.php"
    type: annotation
    

messagesimports:
    resource: "@FMSymSlateBundle/Controller/MessagesImportController.php"
    type: annotation
 
translationsimports:
    resource: "@FMSymSlateBundle/Controller/TranslationsImportController.php"
    type: annotation
 
languages:
    resource: "@FMSymSlateBundle/Controller/LanguageController.php"
    type: annotation