homepage:
    resource: "@FMSymSlateBundle/Controller/DefaultController.php"
    type: annotation

packs:
    resource: "@FMSymSlateBundle/Controller/PackController.php"
    type: annotation
    
messagesimports:
    resource: "@FMSymSlateBundle/Controller/MessagesImportController.php"
    type: annotation
 
translationsimports:
    resource: "@FMSymSlateBundle/Controller/TranslationsImportController.php"
    type: annotation
 
languages:
    resource: "@FMSymSlateBundle/Controller/LanguageController.php"
    type: annotation
    
translate:
    resource: "@FMSymSlateBundle/Controller/TranslateController.php"
    type: annotation
    
submissions:
    resource: "@FMSymSlateBundle/Controller/TranslationSubmissionController.php"
    type: annotation
    
exports:
    resource: "@FMSymSlateBundle/Controller/PackExportController.php"
    type: annotation
    
countrylanguages:
    resource: "@FMSymSlateBundle/Controller/CountryLanguageController.php"
    type: annotation
    
countries:
    resource: "@FMSymSlateBundle/Controller/CountryController.php"
    type: annotation

userlanguages:
    resource: "@FMSymSlateBundle/Controller/UserLanguageController.php"
    type: annotation
    
tasks:
    resource: "@FMSlowShowBundle/Controller/TaskController.php"
    type: annotation

