<?php

namespace FM\SymSlateBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends EntityRepository
{
	public function computeStatistics($country_fields)
	{
		if($country = $this->findOneBy($country_fields))
		{
			if($pack = $this->getEntityManager()->getRepository('FMSymSlateBundle:Pack')->findOneBy(array('is_current' => true)))
			{
				$coverage = 0;
				$denominator = 0;
				foreach($country->getCountryLanguages() as $country_language)
				{
					$pct   = (double)$country_language->getPercent();
					$denominator += $pct;
					$stats = $this->getEntityManager()->getRepository('FMSymSlateBundle:Pack')->computeStatistics($pack->getId(), $country_language->getLanguageId());
					$total = $stats['statistics'][null]['percent'];
					$coverage += (double)$total * $pct;
				}
				$coverage = $coverage / $denominator;
				return $coverage;
			}
			else return 0;
		}
		else return 0;
	}
}
