<?php

namespace FM\SymSlateBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CurrentTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrentTranslationRepository extends EntityRepository
{
	public function actualizeWith($translation, $logger=null)
	{
		if($logger)$logger->info("Actualizing translation with translation with key: ".$translation->getMkey());
		$query = $this->getEntityManager()->createQuery('SELECT c from FMSymSlateBundle:Classification c JOIN c.message m WHERE m.mkey = :mkey');
		$query->setParameter('mkey',$translation->getMkey());
		$classifications = $query->getResult();
		if($logger)$logger->info("CurrentTranslations to create or update: ".count($classifications));
		foreach($classifications as $classification)
		{
			if($ct = $this->findOneBy(array("classification_id" => $classification->getId(), "language_id" => $translation->getLanguage()->getId())))
			{
				//update CurrentTranslation
				//deferred till after the if because this is done in both cases
			}
			else
			{
				$ct = new CurrentTranslation();
				$ct->setClassification($classification);
				$ct->setLanguageId($translation->getLanguage()->getId());
			}
			
			$ct->setTranslation($translation);
			$this->getEntityManager()->persist($ct);
		}
	}
}
