<?php

namespace FM\SymSlateBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IgnoredSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IgnoredSectionRepository extends EntityRepository
{
	public function get($pack_id, $language_id)
	{
		$q = $this->getEntityManager()->createQuery("SELECT s.category, s.section FROM FMSymSlateBundle:IgnoredSection s WHERE s.pack_id=:pack_id AND s.language_id=:language_id");
		$q->setParameter('pack_id'		, $pack_id);
		$q->setParameter('language_id'	, $language_id);

		$res = array();

		foreach($q->getResult() as $row)
		{
			if(!isset($res[$row['category']]))
			{
				$res[$row['category']] = array();
			}
			if(!isset($res[$row['category']][$row['section']]))
			{
				$res[$row['category']][$row['section']] = true;
			}
		}

		return $res;
	}
}
