<?php

namespace FM\SymSlateBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CurrentTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageRepository extends EntityRepository
{
	public function getLanguageNames()
	{
		$languageNames = array();
		foreach($this->findAll() as $language)
		{
			$languageNames[$language->getId()] = $language->getName();
		}
		return $languageNames;
	}
}
	