<?php

namespace FM\SymSlateBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessagesImportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessagesImportRepository extends EntityRepository
{
	public function saveMessages($messages_import, $messages, $logger = null)
	{
		$em = $this->getEntityManager();
		
		$em->getConnection()->getConfiguration()->setSQLLogger(null);
		
		$mr = $em->getRepository('FMSymSlateBundle:Message');
		$cr = $em->getRepository('FMSymSlateBundle:Classification');
		$sr = $em->getRepository('FMSymSlateBundle:Storage');
		
		foreach($messages as $message)
		{
			$classification_data = $message->classification_data;
			$storage_data = $message->storage_data;
			
			//create the message
			if($tmp = $mr->findOneByMkey($message->getMkey()))
			{
				//do nothing if the message is already there
				$message = $tmp;
			}			
			else
			{
				$message->setMessagesImport($messages_import);
				$em->persist($message);
			}
			
			//create OR UPDATE the classification
			if($classification = $cr->findOneBy(array("pack_id" => $messages_import->getPackId(), "message_id" => $message->getId())))
			{
				
			}
			else
			{
				$classification = new Classification();
				$classification->setMessagesImport($messages_import);
				$classification->setPack($messages_import->getPack());
				$classification->setMessage($message);
			}
			
			$classification->setCategory($classification_data["category"]);
			$em->persist($classification);
			
			//create OR UPDATE the storage
			if($storage = $sr->findOneBy(array("pack_id" => $messages_import->getPackId(), "message_id" => $message->getId())))
			{
				
			}
			else
			{
				$storage = new Storage();
				$storage->setMessagesImport($messages_import);
				$storage->setPack($messages_import->getPack());
				$storage->setMessage($message);
			}
			
			$storage->setMethod($storage_data['method']);
			$storage->setPath($storage_data['path']);
			$storage->setCategory($storage_data['category']);
			$storage->setCustom($storage_data['custom']);
			
			$em->persist($storage);
			
			if($logger)$logger->info('Size of unit of work: ' . $em->getUnitOfWork()->size());
			
			$em->persist($em->merge($messages_import));
			$em->persist($em->merge($messages_import->getPack()));
			$em->flush();
			
			$em->clear();
			
		}
	}
}
