<?php

namespace FM\SymSlateBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * PackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PackRepository extends EntityRepository
{
	public function getMessagesWithTranslations($pack_id, $language_id, $query_options = array(), $pagination_options = array())
	{
		$default_query_options = array(
			"empty" => "ONLY", 				// possible values are: ONLY, EXCEPT, anything else is treated as "take empty or non-empty"
			"category" => null,				// all categories
			"section" => null,				// all sections
			"subsection" => null,			// all subsections
			"source_language_id" => null	// language from which to translate
		);
		
		$default_pagination_options = array(
			"page_size" => 25,
			"page" => 1
		);
		
		$query_options = array_merge($default_query_options, $query_options);
		$pagination_options = array_merge($default_pagination_options, $pagination_options);
		
		if(isset($query_options['source_language_id']))
		{
			if($lang = $this->getEntityManager()->getRepository('FMSymSlateBundle:Language')->findOneById($query_options['source_language_id']))
			{
				if($lang->getCode() == 'en')
				{
					$query_options['source_language_id'] = null;
				}
			}
			else $query_options['source_language_id'] = null;
		}
		
		$qb    = $this->getEntityManager()->createQueryBuilder();
		
		if(!$query_options['source_language_id'])
		{	
			$qb->select(array('c','m','ct','t'));
		}
		else
		{
			$qb->select(array('c','m','ct','t', 'sct', 'st'));
		}
		
		$qb->from('FMSymSlateBundle:Classification','c')
		   ->innerJoin('c.message', 'm')
		   ->leftJoin ('m.current_translations','ct','WITH','ct.language_id = :language_id')
		   ->leftJoin ('ct.translation','t');
			
		if($query_options['source_language_id'])
		{
			$qb->leftJoin ('m.current_translations','sct','WITH','sct.language_id = :source_language_id')
		       ->leftJoin ('sct.translation','st');
		}	
			
		$qb->where('c.pack_id = :pack_id');
			
		if($query_options["empty"] == "ONLY")
		{
			$qb->andWhere('t.id IS NULL');
		}
		else if($query_options["empty"] == "EXCEPT")
		{
			$qb->andWhere('t.id IS NOT NULL');
		}
		
		if($query_options["category"] !== null)
		{
			$qb->andWhere("c.category = :category");
		}
		if($query_options["section"] !== null)
		{
			$qb->andWhere("c.section = :section");
		}
		if($query_options["subsection"] !== null)
		{
			$qb->andWhere("c.subsection = :subsection");
		}
		
		$query = $qb->getQuery();
								   
		$query->setParameter('pack_id', $pack_id);
		$query->setParameter('language_id', $language_id);
		
		if($query_options["category"] !== null)
		{
			$query->setParameter('category', $query_options["category"]);
		}
		if($query_options["section"] !== null)
		{
			$query->setParameter('section', $query_options["section"]);
		}
		if($query_options["subsection"] !== null)
		{
			$query->setParameter('subsection', $query_options["subsection"]);
		}
		if($query_options['source_language_id'])
		{
			$query->setParameter('source_language_id', $query_options["source_language_id"]);
		}
		
		$query->setMaxResults((int)$pagination_options["page_size"]);
		$query->setFirstResult(((int)$pagination_options["page"]-1)*((int)$pagination_options["page_size"]));
		
		
		$paginator = new Paginator($query, true);
		
		$messages = array();
			
		if($sid = $query_options['source_language_id'])
		{
			
		}
			
		foreach($paginator as $classification)
		{
			
			$translation = '';
			$text        = null;
			$translation_id = null;
			
			$message = $classification->getMessage();

			$cts     = $message->getCurrentTranslations();

			
			/**
			 * There are 0 - 2 $cts depending on
			 *  -whether we requested a source language translation
			 *  -whether the source and dest language translations were found
			 */

			foreach($cts as $ct)
			{
				//get the translation
				if($ct->getLanguageId() == $language_id)
				{
					$translation    = $ct->getTranslation()->getText();
					$translation_id = $ct->getTranslation()->getId();
				}
				//get the message translation if required
				if(isset($query_options['source_language_id']) and $ct->getLanguageId() == $query_options['source_language_id'])
				{
					$text = $ct->getTranslation()->getText();
				}
			}

			//set the default message text if message translation in source language was not found or not requested
			if(null === $text)$text = $message->getText();
			
			$messages[$classification->getCategory()][$classification->getSection()][$classification->getSubSection()][] = array(
				"text" => $text,
				"translation" => $translation,
				"translation_id" => $translation_id,
				"type" => $message->getType(),
				"classification_id" => $classification->getId(),
				"message_id" => $message->getId()
			);
				
				//echo "<p>".$message->getText()."</p>";
		}
		
		$pagination = array(
			'total_count' => count($paginator),
			'page' => $pagination_options['page'],
			'page_size' => $pagination_options['page_size'],
			'page_count' => round((int)count($paginator)/(int)$pagination_options['page_size'])
		);
		
		return array('messages' => $messages, 
					 'pagination' => $pagination
					);
		
	}

	public function getStoragesWithTranslations($pack_id, $language_id)
	{
		$qb = $this->getEntityManager()->createQueryBuilder();
		$qb->select(array('s','m','ct','t'))
		   ->from('FMSymSlateBundle:Storage', 's')
		   ->innerJoin('s.message', 'm')
		   ->innerJoin('m.current_translations', 'ct')
		   ->innerJoin('ct.translation', 't')
		   ->where('s.pack_id = :pack_id')
		   ->andWhere('ct.language_id = :language_id');
		   
		$query = $qb->getQuery();
		$query->setParameter('pack_id', $pack_id);
		$query->setParameter('language_id', $language_id);
		
		return $query->getResult();
		
	}

	public function computeStatistics($pack_id, $language_id)
	{	
		$query = $this->getEntityManager()->createQuery(
		"SELECT c.category, count(c.id) as total, count(ct.id) as translated 
		 FROM FMSymSlateBundle:Classification c 
		 LEFT JOIN c.message m
		 LEFT JOIN m.current_translations ct
		 WITH ct.language_id = :language_id
		 WHERE c.pack_id = :pack_id
		 GROUP BY c.category
		"		
		);
		$query->setParameter(':language_id',$language_id);
		$query->setParameter(':pack_id',$pack_id);
		$results = $query->getResult();
		
		//print_r($results);
		
		$stats = array(null => array('total' => 0, 'translated' => 0, 'percent' => 0));
		$cats  = array(null);
		
		foreach($results as $row)
		{
			$cats[] = $row['category'];
			$stats[$row['category']] = array('total' => (int)$row['total'], 'translated' => (int)$row['translated'], 'percent' => 100 * (int)$row['translated'] / (int)$row['total'] );
			$stats[null]['total'] += (int)$row['total'];
			$stats[null]['translated'] += (int)$row['translated'];
		}
		
		$stats[null]['percent'] = 100 * $stats[null]['translated'] / $stats[null]['total'];
		
		return array("categories" => $cats, "statistics" => $stats);
	}

	public function computeAllStatistics($pack_id, $force_refresh=false, $refresh_interval=1)
	{
		$pack = $this->find($pack_id);

		
		if(!$force_refresh and null !== $pack->getStatisticsUpdated())
		{
			$now   = new \DateTime("now");
			$delta = $now->diff($pack->getStatisticsUpdated());
			$minutes = ($delta->days * 24 + $delta->h) * 60 + $delta->i;

			if($minutes < $refresh_interval)
			{
				$result = json_decode($pack->getStatistics(),true);
				//print_r($result);
				return $result;
			}
		}

		$stats = array();
		$cats  = null;
		foreach($this->getEntityManager()->getRepository('FMSymSlateBundle:Language')->findAll() as $language)
		{
			$st   = $this->computeStatistics($pack_id, $language->getId());
			$cats = $st['categories'];
			$stats[$language->getAName()] = array('code' => $language->getCode(), 'statistics' => $st['statistics']);
		}
		$result = array('categories' => $cats, 'statistics' => $stats);

		$pack = $this->find($pack_id);
		$pack->setStatistics(json_encode($result));
		$pack->setStatisticsUpdated(new \DateTime("now"));

		$this->getEntityManager()->persist($pack);
		$this->getEntityManager()->flush();

		return $result;
	}
	
	public function setCurrent($pack_id)
	{
		$this->getEntityManager()->createQuery("UPDATE FMSymSlateBundle:Pack p SET p.is_current = CASE WHEN p.id = :pack_id THEN true ELSE false END")
								 ->setParameter('pack_id',$pack_id)
								 ->getResult();
	    
	}
	
	public function getPackNames()
	{
		$packNames = array();
		foreach($this->findAll() as $pack)
		{
			$packNames[$pack->getId()] = $pack->getFullName();
		}
		return $packNames;
	}

}
