<?php

namespace FM\SymSlateBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TranslationsImportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TranslationsImportRepository extends EntityRepository
{
	public function saveTranslations($translations_import_id, $logger = null)
	{
		$translations_import = $this->findOneById($translations_import_id);
		$translations        = $translations_import->buildTranslation();
	}
}
