<?php

namespace FM\SymSlateBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TranslationSubmissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TranslationSubmissionRepository extends EntityRepository {
	public function submitTranslation($user_id, $message_id, $classification_id, $previous_translation_id, $language_id, $text) {
		$data = array('success' => false);

		/*
		 * Check the access rights
		 *
		 */

		$user = $this -> getEntityManager() -> getRepository('FMSymSlateBundle:User') -> findOneById($user_id);
		$language = $this -> getEntityManager() -> getRepository('FMSymSlateBundle:Language') -> findOneById($language_id);
		$message = $this -> getEntityManager() -> getRepository('FMSymSlateBundle:Message') -> findOneById($message_id);

		if (!$user or !$language or !$user -> canTranslateInto($language)) {
			$data['error_message'] = "Something went wrong, most probably you are not authorized to perform this action.";
			return $data;
		}

		/*
		 * Check that we have a text
		 *
		 */

		if (strlen(trim($text)) == 0) {
			$data['error_message'] = "Cannot submit empty translation!";
			return $data;
		}

		/*
		 * Create The New Translation
		 *
		 * If there was a translation before, check to see if it is the same text and if so duplicate it and put the user as reviewer
		 * Else, create the translation and set the current user as the author
		 *
		 * If a translation_id was submitted set the new translation's previous_translation_id to this id
		 *
		 */

		//see if a translation with the same text exists

		$tr = $this -> getEntityManager() -> getRepository('FMSymSlateBundle:Translation');

		if ($previous_translation_id and ($previous_translation = $tr -> findOneById($previous_translation_id)) and ($previous_translation -> getText() == $text)) {
			$translation = clone $previous_translation;
			$translation -> setReviewer($user);
		} else {
			$translation = new Translation();
			$translation -> setLanguage($language);
			$translation -> setText($text);
			$translation -> setMkey($message -> getMkey());
		}

		$translation -> setPreviousTranslationId($previous_translation_id);

		$this -> getEntityManager() -> persist($translation);

		/*
		 * For all packs, create or update the CurrentTranslation with the one we just got.
		 */

		$actualization = $this -> getEntityManager() -> getRepository('FMSymSlateBundle:CurrentTranslation') -> actualizeWith($translation);
		$data['actualization'] = $actualization;
		
		/*
		 * Finally create the submission TODO
		 */
		
		
		$submission = new TranslationSubmission();
		$submission->setUser($user);
		$submission->setTranslation($translation);
		$translation->setTranslationSubmission($submission);

		$this->getEntityManager()->persist($submission);
		$this->getEntityManager()->persist($translation);
		
		//if we got there, don't think twice, it's allright
		$data['success'] = true;

		return $data;
	}

}
